website/models.py
from datetime import timezone
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.string(150), unique=True)
    password = db.Column(db.string(150))
    notes = db.relationship('Note')

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path

db = SQLAlchemy()

DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Note
    

    create_database(app)
    
    
    return app

def create_database(app):
    if not path.exists('Nov21/' + DB_NAME):
        db.create_all(app=app)
        print("Created Database!")

website/auth.py
from flask import Blueprint, render_template, request
from flask.helpers import flash

auth =  Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    data = request.form
    print(data)
    return render_template("login.html", boolean=True)

@auth.route('/logout')
def logout():
    return "<p> logout </p>"

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')

        if len(username) < 2:
            flash("Username must be more than 2 Letters", category='error')
        elif len(password) < 7:
            flash("password must be more than 7 letters", category='error')
        else:
            flash("Account Created!", category='success')
            #add user to the database
    return render_template("sign-up.html")

website/views.py
from flask import Blueprint, render_template

views =  Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html")
    

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title class="white">{% block title %} Code_Website {% endblock %} </title>
    <link rel = "stylesheet" type="text/css" href="{{ url_for('static',filename='/style.css') }}">
    <meta charset="UTF-8">
    <meta name="description" content="Code_Win Tech Blog">
    <meta name="author" content="Code_Win">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="styles"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="styles"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
</head>
<style>
    .center {
        text-align: center;
    }
    .colorwhite {
        color: rgb(163, 163, 163);
    }
    .fontsize{
        font-size: large;
    }
    .fontlg{
        font-size: 40px;
    }
    #dosis{
        font-family: dosis;
    }
    
</style>
<body>
    <h1 class="center colorwhite fontlg" id="dosis">Code_Website</h1>
    
    <div class="div1">
        <div class="center-button">
        </div>
    </div>
    <div class="white" id="dosis">
        <div class="topnav">
            <div class="centerdiv">
                <a class="active" href="/">Home</a>
            <a href="/blogs">Blogs</a>
            <a href="/login">Login</a>
            <a href="/sign-up">Sign Up</a>
        </div>
            
          </div>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <ul class=flashes>
        {% for category, message in messages %}
            <li class="{{category}}">{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock %}
    
    
    
</body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %} Home - Code_Website {% endblock %}


{% block content %}
    <div class="div2 white fontsize" id="dosis">
       
        
        <h1>
           Bit of Background<img src="/static/Images/coding.png" width="280" height="280" style="float: right;">
       </h1>
       
       <div class="div-p white fontsize" id="dosis">
        
        <p>
            Hello!
        </p>
        
        <p>
            My Name is Code_Win, a high schooler from California that REALLY likes coding, volleyball, and obviously video games.
        </p>
        
        <p>
            One of my main passions is learning about a lot of things at the same time. I love learning about new things such as linux, operating systems, and a bunch of different coding languages.
        </p>
            
        <p>
            I also listen to a lot of music. Some artists that I listen to are AJR, Saint Motel, and Cosmo Sheldrake.
        </p>
        <p>
            Some other video games that I play are No Man's Sky, Minecraft, and Trackmania.
        </p>
        <p>
            Right now I am working on a series of projects for my ninth grade year. This is actually my first project that I am going to post on GitHub.
        </p>
        <p>
            &nbsp;
        </p>
       </div>
       
    </div>
    <div class="div3 white fontsize right" id="dosis">
         <h1>
             Experience
         </h1>  
         <div class="div-p white fontsize" id="dosis">
             <p>
                 I have been coding in python for a few years now, mostly on and off from websites.<img src="/static/Images/vsc.png" width="300" height="300" style="float: left;">
             </p>
             <p>
                 After that, in around 2018, I started working on Unity with C# which was also on and off. 
             </p>
             <p>
                 In 7th grade, I enrolled in a basic coding course in my school, which taught me basic html code, and taught me javascript. 
             </p>
             <p>
                 However, it was incredibly simple, and was used on a simple coding website.
             </p>
             <p>
                 For the next few years, I kind of switched back and forth from coding, and didn't really make much progress in my skill.
             </p>
             <p>
                 However, just recently, in October, I started a system where, each month, I have a project to complete by the end of the month. 
             </p>
             <p>
                 This being the first project, I started off by making a simple local webserver in python and connecting it to html.
             </p>
         </div> 


    </div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %} Login - Code_Website {% endblock %}


{% block content %}
<form method="post">
    <div align="center">
        <div align="center" class="border dosis">
           <div class="header dosis">
              <h1 class="word">Log In</h1>
           </div></br></br></br>
          <h2 class="word dosis">
              <form action="{{ url_for('auth.sign_up') }}" method="post">
                <div class="msg dosis">{{ msg }}</div>
                  <input id="username" name="username" type="text" placeholder="Enter Your Username" class="textbox"/></br></br>
                  <input id="password" name="password" type="password" placeholder="Enter Your Password" class="textbox"/></br></br>
                  <input type="submit" class="btn" value="Log In"></br>
              </form>
          </h2>
          <p class="bottom" >Don't have an account?  <a class="bottom" href="{{url_for('auth.sign_up')}}"> Register here!</a></p>
        </div>
      </div>    
</form>
{% endblock %}

website/templates/sign-up.html
{% extends "base.html" %}
{% block title %} Sign Up - Code_Website {% endblock %}


{% block content %}
<form method="post">
    <h3 align="center">
        Sign Up
    </h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name">
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="text" class="form-control" id="password1" name="password1" placeholder="Enter Password">
    </div>
    <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input type="text" class="form-control" id="password2" name="password2" placeholder="Confirm Password">
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}